Режим "Крушение"
RU-CMSS13/RU-CMSS13 pull request #153
Opened 2024-02-29 12:18 UTC by BlackCrystalic

# About the pull request

Был добавлен режим крушения, на карту Кхами Баренс (на данный момент он имеет все нужные ландмарки только там)
Запустить игру более невозможно, если не выполнены условия для запуска раунда в автоматическом режиме (1 морпех, 1 ксеноморф), но все еще можно запустить в обход через админскую кнопку старта раунда.

# Explain why it's good for the game

Лоупоп режим... наверное интересно.

# Changelog
:cl: BlackCrystalic
add: Crash gamemode and related stuff for it
fix: no more auto game start without xenoplayers
/:cl:

2024-03-10 13:39 UTC, Chip11-n commented
Могут быть 2 одинаковых спека.

Типо-кас бьет без предупреждения, в том числе и по своим.

Морпехи страдают без скиллов. Может дать памплеты?

Лз нельзя засадить травой даже после прилета маринов.

На карте нет травы, а карта огромна, в итоге что бы засадить хотя бы важные точки, нужно 2-3 дрона раундстартом.

Нет карты, ксены скоординироваться не могут.

Хайв статуса нет, нельзя посмотреть хоть приблизительно кто есть, где есть.

Диски не отображаются на карте (при костыле с квиной)

Колония с самого начала запитана. Зачем? Почему? 

На границах карты удаляются мобы.

Нет универсального ксена, который мог бы и сражаться, и садить траву. На тгмс не просто так есть шрайк.

Ксенам постоянно спамит о новых лярвах, может просто бесконечный спавн без перерывов сделать?

Эволюцию ксенам бы поднять.

2024-04-16 10:40 UTC, Pl3aseJust3ndMySuffering requested changes
Помимо комментов прямо в диффе:
> Check_Crash()

Вот этот прок лучше сделать в lowercase, т.е. check_crash(), читается удобнее.
То же самое с Check_WO()

В остальном - хорошая работа!

2024-04-16 10:40 UTC, Pl3aseJust3ndMySuffering commented on code/__DEFINES/subsystems.dm
Изменение приоритета инициализации тикера ничего не сломало? Стоит начать и закончить раунд и проверить код на рантаймы, просто на всякий случай

2024-04-16 10:40 UTC, Pl3aseJust3ndMySuffering commented on code/modules/admin/topic/topic.dm
Grammar Nazi

**The mode for next round** замени на **The mode for the next round**

2024-04-16 10:40 UTC, Pl3aseJust3ndMySuffering commented on fray-marines/code/game/gamemodes/colonialmarines/crash.dm
> +	to_chat(world, "<span class='round_header'>Ship crashed over - [SSmapping.configs[GROUND_MAP].map_name]! You know all about enemy, time to final battle!</span>")
Grammar Nazi

Замени на **Your ship has crashed over - [SSmapping.configs[GROUND_MAP].map_name]! You know everything about the enemy, time for the final battle!**

2024-04-16 13:23 UTC, Pl3aseJust3ndMySuffering commented on code/__DEFINES/subsystems.dm
Самостоятельная проверка - всё работает.

2024-04-16 13:24 UTC, Pl3aseJust3ndMySuffering approved these changes
Вот теперь всё идеально. Ждём тестмердж

2024-05-02 11:29 UTC, merged