Boot Camp map and new gamemode
RU-CMSS13/RU-CMSS13 pull request #303
Opened 2024-11-03 05:58 UTC by Arom-beep

# About the pull request

Добавление новой карты для обучения новых морпехов с новым гейммодом!

# Explain why it's good for the game

Обучение новеньких всегда трудное дело, но с этой картой и этим гейммодом можно испытать любое оружие и технику, потренироваться в стрельбе и строительстве.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

</details>

# Changelog

:cl:
add: Added new gamemod for Boot Camp
mapadd: Boot camp map added
/:cl:

2024-11-25 10:25 UTC, Noname995 requested changes
После этого в мерж

2024-11-25 10:25 UTC, Noname995 commented on colonialmarines.dme
> +#include "code\game\area\bootcamp.dm"
В инклюды
```suggestion
```

2024-11-25 10:25 UTC, Noname995 commented on colonialmarines.dme
> +#include "code\game\gamemodes\colonialmarines\bootcamp.dm"
```suggestion
```

2024-11-25 10:25 UTC, Noname995 commented on code/game/gamemodes/colonialmarines/bootcamp.dm
> +/datum/game_mode/bootcamp
Закинь в кор ру пожалуйста
```suggestion
/datum/game_mode/bootcamp
```

2024-11-25 10:25 UTC, Noname995 commented on code/game/area/bootcamp.dm
> +/area/BootCamp
Закинь в кор ру пожалуйста
```suggestion
```

2024-11-26 14:47 UTC, Arom-beep commented
Может быть когда время будет я переделаю

2024-12-19 12:34 UTC, Arom-beep commented
Этот ПР я вообще думаю переработать капитально, т.к карта и сама идея буткемпа не оправдала себя.
Есть мысли чтобы сделать эту карту доступной для гостов и для этого карту надо будет переделать, и в принципе код переделать
Так что я думаю вывести её из тестмержа точно и положить в дальний ящик.

2025-01-27 11:10 UTC, closed without merging

2025-01-27 11:11 UTC, Arom-beep commented
Режим оказался не актуален, жалко потраченых сил на карту