Mech-drop-magazine-button-kostil
RU-CMSS13/RU-CMSS13 pull request #305
Opened 2024-11-25 09:36 UTC by Lentye

# About the pull request
Фикс кнопке сброса магазина на стандартные +1/-1 строчку
Смешные комменты включены

# Explain why it's good for the game

Позволяет полноценно сбрасывать меху магазины
# Testing Photographs and Procedure
отказано,лень
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
fix: починил кнопку выброса магазина меха
/:cl:

2024-11-25 10:17 UTC, Noname995 requested changes
Кину в ТМы до убирания комментов

2024-11-25 10:17 UTC, Noname995 commented on core_ru/code/modules/vehicles/walker_verbs.dm
> +/obj/vehicle/walker/proc/eject_magazine(mob/user_mob) //, obj/item/walker_gun/hardpoint нахуй не нужен второй аргумент; не назначается, а вынуждает игру выбирать его среди ближайших объектов СНАРУЖИ
Воздержись пожалуйста от оскорблений в комментариях кода.
```suggestion
/obj/vehicle/walker/proc/eject_magazine(mob/user_mob)
```

2024-11-25 10:17 UTC, Noname995 commented on core_ru/code/modules/vehicles/walker_verbs.dm
> +	if(!hardpoint) //расчитывался что изначально выбирался до него, но так как мы мудилы, ПЛАН Б(поиска) ТЕПЕРЬ ОСНОВНОЙ;
```suggestion
	if(!hardpoint) //расчитывался что изначально выбирался до него, но, ПЛАН Б(поиска) теперь основной;
```

2024-11-25 10:19 UTC, Noname995 commented
Было бы наверное лучше не искать точку для сброса магазина в отдельном меню, а выбирать точку которая щас активный у меха активная, но это уже на твоё усмотрение

2024-11-25 10:29 UTC, Lentye commented
Так мы же сами убрали выбор текущего оружия, лкм левое, скм-правое, нету смены слота

2024-11-25 10:40 UTC, Lentye commented
P.S. смешные комменты кончились

2024-11-25 13:13 UTC, Noname995 commented
> Так мы же сами убрали выбор текущего оружия, лкм левое оружие, скм-правое оружие, нету смены слота

Пу-пу-пу. Я не знал что у нас волкер не как мультитайл работает

2024-11-25 18:58 UTC, Lentye commented
Был совершен еще один опыт, если убрать еще и первый аргумент, то мы избавимся от еще одного ненужного поиска значения и сразу сделаем проки

2024-11-28 13:15 UTC, Lentye commented on core_ru/code/modules/vehicles/walker_verbs.dm
> +	if(!hardpoint) //расчитывался что изначально выбирался до него, но, ПЛАН Б(поиска) теперь основной;
Если ты про то, что я не поставил вар в проверку, а отдельно- то мне без разницы; если ты про то, что я вывел из аргумента в вары, то из-за наличия аргумента и отсутствия самого аргумента в вызове, прок добавления верба вызывал поиск аргумента из случайных предметов вокруг пилота меха включая AREA, что бесит; в принципе проще оставить навсегда в тест-мердже пока сам создатель меха не придумает что делать с его наработкой...

2024-11-28 13:16 UTC, Lentye commented on core_ru/code/modules/vehicles/walker_verbs.dm
> +	if(!hardpoint) //расчитывался что изначально выбирался до него, но, ПЛАН Б(поиска) теперь основной;
а если про то, что я именно указал что это walker_gun то мне так-же без разницы, оставил напоминанием

2024-11-28 13:24 UTC, Lentye commented on core_ru/code/modules/vehicles/walker_verbs.dm
> +	if(!hardpoint) //расчитывался что изначально выбирался до него, но, ПЛАН Б(поиска) теперь основной;
Идеальным решением было бы, если сам вызов верба учитывал аргументы нужные проку

2024-11-28 13:27 UTC, Lentye commented on core_ru/code/modules/vehicles/walker_verbs.dm
> +	if(!hardpoint) //расчитывался что изначально выбирался до него, но, ПЛАН Б(поиска) теперь основной;
Но как я смотрю add_verb не учитывает аргументы при добавлении, что требует иного метода для решения задачи чем просто вписать нужное

2024-11-28 13:47 UTC, Lentye commented
Дорезал аргумент моба и оставил специально для кристаллика черточку.

2024-11-29 05:46 UTC, Lentye commented on core_ru/code/modules/vehicles/walker_verbs.dm
> +	if(!hardpoint) //расчитывался что изначально выбирался до него, но, ПЛАН Б(поиска) теперь основной;
Какой фикс, проблема не в значениях, а в том, что ИГРА ИЩЕТ ЗНАЧЕНИЕ ПЕРЕД ОБРАБОТКОЙ МЕШАЯ ИГРОКУ, любая строчка кода игнорируется до того, как мы ВЫБЕРЕМ из другого прока аргументы вызову, я 4 часа дебажил чтобы убедиться-это происходит ДО срабатывания наших проков

2024-11-29 05:48 UTC, Lentye commented on core_ru/code/modules/vehicles/walker_verbs.dm
> +	if(!hardpoint) //расчитывался что изначально выбирался до него, но, ПЛАН Б(поиска) теперь основной;
Да, можно выбрать неправильное значение, но если вставлять null,то кусочек кода по поиску всегда выберет адекватные опции необходимого оружия

2024-11-29 05:49 UTC, Lentye commented on core_ru/code/modules/vehicles/walker_verbs.dm
> +	if(!hardpoint) //расчитывался что изначально выбирался до него, но, ПЛАН Б(поиска) теперь основной;
Вот что могло и подойти, это set_range(0) в вызове, чтобы он всегда изнутри

2024-11-29 06:04 UTC, Lentye commented
Пойду тестить опции, нужно проверить комбинации махинаций

2025-01-14 05:45 UTC, blackcrystall commented
В общем, закрыто в пользу более простого фикса (+3 -3 > +16 -5)

2025-01-14 05:45 UTC, closed without merging