Experimental Personal Railgun(EPR) Thundermatch test
RU-CMSS13/RU-CMSS13 pull request #311
Opened 2024-12-17 13:04 UTC by Lentye

# About the pull request

Т4 технология вооружения не требующий скиллов(ушло в комменты, пока не посмотрю на использование марами на тандере)
Тестирование перспективности вещи
Так же хочу сделать потом T4/additional ветку чтобы нормально стояло по позициям

# Explain why it's good for the game
Гейм-Чейнджер, способный так-же, как и садар ломать лица, но дороже по технологической ветке и требующий тех поинты на патроны.

# Testing Photographs and Procedure

<details>

<summary>Screenshots & Videos</summary>

![image](https://github.com/user-attachments/assets/d1b07391-c4df-4aa4-a610-43b28bb64d9d)

![image](https://github.com/user-attachments/assets/49a79a66-439d-44db-b42f-64169ae5ff86)

</details>

# Changelog

:cl:
add: Т4 тест вооружения
/:cl:

2024-12-18 07:47 UTC, Lentye commented
Скорее всего, если реально кто-то потом будет согласен, придется анимировать разгон как у улучшенной насадки на стволы

2024-12-18 22:20 UTC, Noname995 commented
Как насчёт сделать его более заблокированным? (Т.е. к примеру спекам, СЛам и РТО)
Взамен популяризации можно повысить урон. Иначе это просто снайперка, но без уникальных патронов но для всех.

Закину в ТМ сейчас, выше предложения мои :)

2024-12-29 11:45 UTC, Lentye commented
Ты серьезно...

2024-12-29 12:04 UTC, Lentye commented
Ладно, пойдем на второй круг

2024-12-29 12:05 UTC, Lentye commented
Ах,я вообще не так подумал, мм, придеться делать по иному

2024-12-30 08:26 UTC, Lentye commented
Такс, починил что недочинил в первый раз, технологии ушли из комментов в игру, можно уже идти на второй круг тестов ингейм

2025-01-29 10:54 UTC, blackcrystall requested changes
Для начала вот это, потом по балансу узнаем от участников проекта

2025-01-29 10:54 UTC, blackcrystall commented on core_ru/code/modules/cm_tech/techs/marine/tier4/personal_railgun.dm
> +/obj/item/storage/box/kit/EPR
Заглавные буквы, желательно убрать из пути и расписать более понятно кратко что это такое

2025-01-29 10:54 UTC, blackcrystall commented on code/modules/projectiles/gun.dm
> +	var/lineart_ru = FALSE
Это можно вынести в наш модуль

2025-01-29 10:54 UTC, blackcrystall commented on code/modules/asset_cache/asset_list_items.dm
> +		//RUCM START
Можно пожалуйста соблюдать требования к пометке кода? а так же рассказываю секрет, у тебя есть ошибка тут, перечитай еще раз как работает тест этот и тебе потребуется изменить всего НОЛЬ строчек в самом итераторе, и чеке, единственное что добавить просто в пул спрайты из нашей директории

2025-01-29 10:54 UTC, blackcrystall commented on code/__DEFINES/techtree.dm
> +	/datum/tier/four/additional\
Можно пометить наши изменения и закомитить оригинальную 54 строчку?

2025-02-12 11:47 UTC, Lentye commented on code/__DEFINES/techtree.dm
> +	/datum/tier/four/additional\
Неа, по той-же причине что ты сам и кодил без меток, \ исключает возможность вставлять любые символы между строчками включая комменты, иначе скобки считаются несбалансированными, тут или делать игнорируя или везде удалять/комментить "\" символ

2025-03-27 16:47 UTC, closed without merging