#TESTMERGE Крупное обновление ЕРТ карт и Алмайера
RU-CMSS13/RU-CMSS13 pull request #96
Opened 2023-09-28 20:01 UTC by XDinka

# Обновление мостика и стилистические правки ангара. ТЕСТОВОЕ ОБНОВЛЕНИЕ: Добавление ЕРТ баз, удаление спавна с шаттлов, перенос спавна ЕРТ на сами базы.

# Алмайер

Вдохновившись ПРом с офф цмов, я решила адаптировать будущие изменения мостика на опережение. Кроме того, подсмотрев стиль оформления шаттла с TWE ЕРТ базы, слегка переоформила ангар, а именно посадочные платформы челноков Аламо и Нормандия.

## Мостик

В целом, мостик был переработан, стал чуть свободнее и приобрел больший функционал. 

Кабинка командующего операцией стала больше, получила собственные консоли координации на случай отсутствия SO. Часто случалось так, что неким командовать, а носиться по мостику как обезьяна с гранатой - контрпродуктивно. Кроме того, кабинка получила тактическую карту, консоль технологической сети. Внутрь переехал планшет и его шкаф. Целых ЧЕТЫРЕ телефонных линии, чтоб каждый мог дозвониться! Еще больше пространства внутри кабинки! Теперь не придется полковнику пинать бедного капитана, если оба захотят покомандовать!

![image](https://github.com/Fray2/RU-CMSS13/assets/82751385/ec93ceb1-a75e-4804-8747-c83b8ef15948)

Косметическое обновление дает чуть больше воздуха, превращая КИК из проперженной  однушки в настоящую студию в центре Луны.

![image](https://github.com/Fray2/RU-CMSS13/assets/82751385/1644b1b1-6897-45e1-9cfc-23126fdc6228)

Наши инженеры разработали специальный пост МП, как первый оплот против бунтовщиков с возможностью заблокировать доступ к КИКу! Пошлите в задницу проклятых идиотов, что посмели попытаться вломиться к вам, заблокировав им подходы стальными створками! 

![image](https://github.com/Fray2/RU-CMSS13/assets/82751385/92394c5e-b9ee-4897-adb6-175037114153)

Центр получил собственный СМЕС на случай резких перебоев питания! Крайне полезная вещь, спрятанная от посторонних глаз! Берегите ее!

Многие комнатки, APC и вещи поменяли свое местоположение. Пусть большинство из них останется для вас сюрпризом.

## Ангар

![image](https://github.com/Fray2/RU-CMSS13/assets/82751385/818cb5f3-f421-4abf-a555-9e33c880d4df)

Ангар получил перегородки, создающие нишу под челноками для более тщательного осмотра и ремонта, что упростит работу инженерным бригадам.

# ПИЛОТЫ! Своевременно сообщайте о всех проблемах с челноком в случае возникновения таковых! Оперативность решения зависит от вас!

# ЕРТ базы

## Админ уровень

![image](https://github.com/Fray2/RU-CMSS13/assets/82751385/0b0bf65a-0e1d-4712-918f-a3babded8872)

Уровень для администрации заметно увеличился! Добавлены (пока-что) целых 4 ЕРТ базы с полностью функционирующими вендорами и т.п. отвечающие всем стандартам и запросам наших оперативников.

## Чинук 98
![image](https://github.com/Fray2/RU-CMSS13/assets/82751385/8e4cf7f7-3cc3-41b4-b560-8bd03e743700)

Легендарный оперативный штаб реализован на админ уровне для разнообразных целей педального состава. На нем не спавнится ЕРТ и он не используется в обычной ситуации, однако открывает различные возможности для ивентов и суеты!

![image](https://github.com/Fray2/RU-CMSS13/assets/82751385/cc9a0034-39ba-4e10-90aa-aff5ac2788b8)

## Малые ЕРТ базы

Добавлены тематические ЕРТ базы, которые не станут сюрпризом для ветеранов колониальной пехоты. Они не были разработаны мной, а лишь интегрированы. Пусть их внешний вид станет для вас сюрпризом.

## Старая ЕРТ база.

Старая ерт база осталась на месте, однако потеряла свой функционал и теперь служит сугубо в админских целях. Более там не появляются челноки.

# Changelog

:cl:
mapadd: новый админ уровень. Добавлены ЕРТ базы и Геркулес - Чинук 98.
maptweak: добавлен новый мостик, косметический ремап лендинг падов, убраны спавны с самих ЕРТ шаттлов, перенесены на ЕРТ базы.
/:cl:

2023-09-28 20:06 UTC, carrotman2013 commented
Охуенно

2023-09-29 01:35 UTC, XDinka commented
Если чеки пройдут отлично (Я молюсь), это будет действительно вкусное и хорошее обновление. Зафиксила вендуры и мелконедочеты на карте.

2023-09-29 01:38 UTC, XDinka commented
Биба и боба, саунд все сломал

2023-09-29 02:09 UTC, XDinka commented
Слава аллаху. Реди то мердж

2023-09-29 03:32 UTC, XDinka commented
_Саксесы пошли, основные тесты пройдены. У меня хорошее предчувствие_

2023-09-29 03:40 UTC, XDinka commented
Niceee

2023-09-29 04:00 UTC, poleno1232 requested changes

2023-09-29 04:01 UTC, XDinka commented on fray-marines/code/modules/vehicles/walker.dm
> +			to_chat(user, "Вы преврали установку.")
U god damn right partner

2023-09-29 04:02 UTC, XDinka commented on fray-marines/code/modules/vehicles/walker.dm
> +	. += "\n[left ? left.name : "Nothing"] установленно на левой платформе."
> Nothing забыла

Я думала это типа какой нить ебучий прок этот, как его...

2023-09-29 04:03 UTC, XDinka commented on fray-marines/code/modules/vehicles/walker.dm
> +	. += "\n[left ? left.name : "Nothing"] установленно на левой платформе."
Атрибут, во

2023-09-29 04:04 UTC, XDinka commented on fray-marines/code/modules/vehicles/walker.dm
> +	. += "\n[left ? left.name : "Nothing"] установленно на левой платформе."
> Nothing забыла

+= "\n[right ? right.name : "Ничего"] не установлено на правой платформе."

Пойдет?

2023-09-29 09:16 UTC, Wyderar commented on fray-marines/code/modules/vehicles/walker.dm
> +	. += "\n[left ? left.name : "Nothing"] установленно на левой платформе."
Пойдёт

2023-09-29 15:39 UTC, XDinka commented
Ебанная табуляция

2023-09-29 15:41 UTC, XDinka commented
Ну и все... Дело за малым

2023-09-29 15:55 UTC, poleno1232 approved these changes

2023-09-29 17:21 UTC, Wyderar commented
Ну бля, помолясь

2023-09-30 18:46 UTC, Fray2 commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Marines

##### Revision
Origin: 529527d6a1673e83986628ed503b1b9a5065ac02
Pull Request: 0ac582028b2b235b243d80d2816d2aae2b31c6ae
Server: f75946d8e1f721e8be884808ebd4dfbca94ae807

##### Comment

[GitHub Deployments](https://github.com/Fray2/RU-CMSS13/deployments/activity_log?environment=TGS%3A+Marines)
</details>

2023-10-01 20:24 UTC, Fray2 commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Marines

##### Revision
Origin: 529527d6a1673e83986628ed503b1b9a5065ac02
Pull Request: 0ac582028b2b235b243d80d2816d2aae2b31c6ae
Server: bdf6a34beb1a4ef01e95700535ebe82281dbe8ce

##### Comment

[GitHub Deployments](https://github.com/Fray2/RU-CMSS13/deployments/activity_log?environment=TGS%3A+Marines)
</details>

2023-10-02 01:40 UTC, blackcrystall commented
Хорошая идея, но она закончится так же как в оригинале
Маппинг 3/10
Изменения кроме карт бы в отдельный ПР желательно... (лично мое мнение, потому что лишнее в этом пре это)
Тестить лень, но вопрос, проверено что шатлы с открытыми дверями спавнятся? Или на авось...? (как я помню они на CM спавнятся на базах с закрытыми, смешные чубрики не могут войти в шатл)

2023-10-03 13:17 UTC, XDinka commented
Хуй его знает короче, какого хрена у меня проваливаются юнит тесты...

Рантаймы повесились

2023-10-04 15:31 UTC, XDinka commented
@xDanilcusx спасибо папаша за этот мерж конфлик 23тьего года

2023-10-04 17:04 UTC, closed without merging