Плюшевый захватчик для лица
RU-CMSS13/RU-CMSS13 pull request #97
Opened 2023-09-28 20:45 UTC by Noname995

Фэйсхаггер на шлем, только плюшевый, в лодауте, больше разнообразия.
Не сделал в другой файл, потому что onmob на helmet_garb работает очень сложно и нужно вызывать методом спрайт. Я пытался, не смог :(

2023-09-28 20:56 UTC, Noname995 commented
А чё всмысле, а на что он жалуется?

2023-09-29 00:46 UTC, carrotman2013 commented
Сложно объяснить - ни на что толком, все норм

2023-09-29 04:02 UTC, poleno1232 requested changes

2023-09-29 04:02 UTC, poleno1232 commented on code/modules/client/preferences_gear.dm
> +	/datum/gear/helmet_garb/facehuggertoy
Линтер жалуется и просто неправильно

2023-09-29 04:10 UTC, XDinka commented
Блять, а где CL? Ну камон, давайте нормально оформлять ПР... Люди смотрят, стыдно

2023-09-29 11:12 UTC, Noname995 commented on code/modules/client/preferences_gear.dm
> +	/datum/gear/helmet_garb/facehuggertoy
Спасибо!

2023-09-29 11:23 UTC, Wyderar commented
Напиши к ПРу чейнжлог

2023-09-29 11:36 UTC, Noname995 commented
> Напиши к ПРу чейнжлог

Сделал

2023-09-30 01:14 UTC, Fray2 commented
эээээ, мы теперь ТГМЦ?

2023-09-30 06:59 UTC, Noname995 commented
> эээээ, мы теперь ТГМЦ?

Капец. Он и так был в билде, я его просто в лодаут добавил, он доставался только у кабинетов РД на фиоринах. Да и при том что по лору ксеноморфы уже давно как известны всей общественности можно сказать лор-френдли

2023-09-30 18:46 UTC, Fray2 commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Marines

##### Revision
Origin: 529527d6a1673e83986628ed503b1b9a5065ac02
Pull Request: 27b5bb34a33c4a7c148fb4f8e4d8ad5b718a6fb1
Server: f75946d8e1f721e8be884808ebd4dfbca94ae807

##### Comment

[GitHub Deployments](https://github.com/Fray2/RU-CMSS13/deployments/activity_log?environment=TGS%3A+Marines)
</details>

2023-10-01 20:24 UTC, Fray2 commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Marines

##### Revision
Origin: 529527d6a1673e83986628ed503b1b9a5065ac02
Pull Request: 27b5bb34a33c4a7c148fb4f8e4d8ad5b718a6fb1
Server: bdf6a34beb1a4ef01e95700535ebe82281dbe8ce

##### Comment

[GitHub Deployments](https://github.com/Fray2/RU-CMSS13/deployments/activity_log?environment=TGS%3A+Marines)
</details>

2023-10-20 08:23 UTC, Noname995 commented
Не получилось, не фартануло

2023-10-20 08:23 UTC, closed without merging