Make HPR meta again.
RU-CMSS13/RU-CMSS13 pull request #99
Opened 2023-09-29 11:54 UTC by Noname995

Делаю ХПР чуть более хорошим в бою. Делаем из неё саппорт-винтовку на передовой
:cl:
balance: Урон холотаргета немного уменьшен, повышение урона повышенно, количество стаков повышено
/:cl:

2023-10-01 11:07 UTC, Noname995 commented
А што не так?

2023-10-02 01:42 UTC, blackcrystall commented
> А што не так?

Ты сделал имбу, что не понятного? (тестил на локалке хотя бы исходную версию vs новую версию?)
А то что прокликали баг, это СКИЛ ИШШУЙ.

2023-10-02 07:47 UTC, Mr-Pickles-beep commented
> > А што не так?
> 
> Ты сделал имбу, что не понятного? (тестил на локалке хотя бы исходную версию vs новую версию?) А то что прокликали баг, это СКИЛ ИШШУЙ.

Предлагаю принять таблеточки и уйти на покой and you can cry about it.

2023-10-02 11:28 UTC, xDanilcusx requested changes

2023-10-03 11:59 UTC, xDanilcusx requested changes

2023-10-03 11:59 UTC, xDanilcusx commented on code/datums/components/bonus_damage_stack.dm
> +/datum/component/bonus_damage_stack/proc/get_bonus_damage(mob/M, list/damage_data) // 30% damage bonus at most
20%

2023-10-03 11:59 UTC, xDanilcusx commented on code/datums/components/bonus_damage_stack.dm
> +	var/bonus_damage_cap = 300
Слишком ёбнуто, меняй на 200 как предлагали

2023-10-03 12:08 UTC, Noname995 commented on code/datums/components/bonus_damage_stack.dm
> +	var/bonus_damage_cap = 300
30% урона слишком много?

2023-10-03 12:09 UTC, Noname995 commented on code/datums/components/bonus_damage_stack.dm
> +	var/bonus_damage_cap = 300
Кап это же максимальное количество % урона?

2023-10-03 17:04 UTC, xDanilcusx commented on code/datums/components/bonus_damage_stack.dm
>  	L += "Bonus Damage Taken: [bonus_damage_stacks * 0.1]%"
ты забыл про строчку, отвечающую за описание (здесь написано 0.1 что на деле пиздёж, нужно 0.2)

2023-10-03 22:46 UTC, Noname995 commented
💀 Какие мерж конфликты из за описания 💀

2023-10-05 08:41 UTC, Noname995 commented
Когда мерж? Хочу с голотаргетами нормальными хотя бы сыграть

2023-10-14 14:02 UTC, xDanilcusx commented
> @xDanilcusx что тут в итоге то?

до 20 вернёт и можно мержить, 25% выдавать было слишком ёбнуто

2023-10-15 09:33 UTC, Noname995 commented
Вчера был раунд с ХПРками, взяли все ХПРки из карго и всёровно ксеномажоры. Не понимаю в чём имбовость, не услышал даже ни одной претензии ни единого ксеноморфа "почему меня так быстро убили" и т.д.

2023-10-16 18:37 UTC, merged